spring:
    profiles:
        group:
            "local": "local,common"
            "product": "product,common"
---
spring:
    config:
      activate:
          on-profile: common
    application:
        name: ShortURL
    messages:
        encoding: UTF-8
server:
    port: 80
jwt:
    secret: "SHORT_URL_API_JWT_TOKEN_SECRET_KEY_VALUE"
    access:
        #expiration: 300000 #5분 (5 * 60) * 1000
        expiration: 864000000 #10일 (60 * 60 * 24 * 10) * 1000
        header: "X-AUTH-TOKEN"
    refresh:
        expiration: 864000000 #10일 (60 * 60 * 24 * 10) * 1000
        header: "X-REFRESH-TOKEN"
---
spring:
    config:
        activate:
          on-profile: local
    redis:
        host: localhost
        port: 6379
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                web-allow-others: true
    datasource:
        driver-class-name: org.h2.Driver
        url: "jdbc:h2:mem:spring_assignments;MODE=MYSQL;"
        username: sa
        password:
        hikari:
            minimum-idle: 1
            maximum-pool-size: 5
            pool-name: H2_DB
    sql:
        init:
            platform: h2
    jpa:
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                format_sql: true
                show_sql: true
        defer-datasource-initialization: true
domain: "http://localhost:80/"
---
spring:
    config:
        activate:
            on-profile: product
    redis:
        host: 172.17.0.3
        port: 6379
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${DATASOURCE_URL}?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
        username: ${DATASOURCE_USERNAME}
        password: ${DATASOURCE_PASSWORD}
        hikari:
            minimum-idle: 1
            maximum-pool-size: 5
            pool-name: MYSQL_DB
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: false
                show_sql: false
        defer-datasource-initialization: true
domain: "http://localhost:80/"